/**
 * Drift guard for MCP client config generators.
 *
 * Single source of truth: `src/constants/mcp-public-config.json`.
 * This test asserts that the pre-generated artifacts in `generated/` reflect
 * the JSON contents. If a future change to the JSON is not propagated to the
 * PowerShell renderer (`scripts/windows/gen-mcp-config.ps1`) or to the admin
 * UI runtime generator, this test fails before the drift hits production.
 *
 * Failure means one of:
 *   - The JSON was updated but `generated/*.toml` was not regenerated
 *     (run `make -f Makefile.win apply-config` or the PS script directly).
 *   - The PS script no longer reads from the JSON (regression in gen-mcp-config.ps1).
 *   - Someone hand-edited `generated/*.toml` (don't — it is autogenerated).
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect } from 'vitest';

import mcpPublicConfig from '../../src/constants/mcp-public-config.json' with { type: 'json' };

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// tests/admin/ → mcp-server/ → typescript/ → src/ → repo root
const REPO_ROOT = resolve(__dirname, '..', '..', '..', '..', '..');

function expectedToolsLine(): string {
  const toolsToml = mcpPublicConfig.publicTools.map((t) => `"${t}"`).join(', ');
  return `enabled_tools = [${toolsToml}]`;
}

describe('mcp-public-config drift guard', () => {
  describe('publicTools is mirrored in generated/ artifacts', () => {
    const artifacts = [
      'generated/codex_config.workspace-qdrant.toml',
      'generated/codex_config.workspace-qdrant.fastembed.toml',
    ];

    for (const rel of artifacts) {
      it(`${rel} has the canonical enabled_tools line`, () => {
        const path = resolve(REPO_ROOT, rel);
        if (!existsSync(path)) {
          // Fresh clone — artifact has not been generated yet. Skip rather than
          // fail; CI in such a state should run the PS script first.
          console.warn(`[drift-guard] skip: ${rel} not present (run apply-config to generate)`);
          return;
        }
        const content = readFileSync(path, 'utf8');
        expect(content).toContain(expectedToolsLine());
      });
    }
  });

  describe('codex timeouts mirror the JSON', () => {
    it('startup_timeout_sec is a positive integer', () => {
      expect(Number.isInteger(mcpPublicConfig.codex.startup_timeout_sec)).toBe(true);
      expect(mcpPublicConfig.codex.startup_timeout_sec).toBeGreaterThan(0);
    });
    it('tool_timeout_sec is a positive integer', () => {
      expect(Number.isInteger(mcpPublicConfig.codex.tool_timeout_sec)).toBe(true);
      expect(mcpPublicConfig.codex.tool_timeout_sec).toBeGreaterThan(0);
    });

    it('generated/codex_config.workspace-qdrant.toml uses JSON timeouts', () => {
      const path = resolve(REPO_ROOT, 'generated/codex_config.workspace-qdrant.toml');
      if (!existsSync(path)) {
        console.warn('[drift-guard] skip: generated/codex_config.workspace-qdrant.toml not present');
        return;
      }
      const content = readFileSync(path, 'utf8');
      expect(content).toContain(`startup_timeout_sec = ${mcpPublicConfig.codex.startup_timeout_sec}`);
      expect(content).toContain(`tool_timeout_sec = ${mcpPublicConfig.codex.tool_timeout_sec}`);
    });
  });

  describe('publicTools ⊆ KNOWN_TOOLS (tool-dispatcher accepts every public tool)', () => {
    // Re-derive what tool-dispatcher.ts computes to confirm the union is consistent.
    it('no public tool is missing from the server registry', () => {
      const knownTools = [...mcpPublicConfig.publicTools, ...mcpPublicConfig.internalTools];
      for (const pub of mcpPublicConfig.publicTools) {
        expect(knownTools).toContain(pub);
      }
    });
  });
});
