/**
 * Drift guard for MCP client config generators.
 *
 * Single source of truth: `src/constants/mcp-public-config.json`.
 * This test asserts that the pre-generated artifacts in `generated/` reflect
 * the JSON contents. If a future change to the JSON is not propagated to the
 * PowerShell renderer (`scripts/windows/gen-mcp-config.ps1`) or to the admin
 * UI runtime generator, this test fails before the drift hits production.
 *
 * Failure means one of:
 *   - The JSON was updated but `generated/*.toml` was not regenerated
 *     (run `make -f Makefile.win apply-config` or the PS script directly).
 *   - The PS script no longer reads from the JSON (regression in gen-mcp-config.ps1).
 *   - Someone hand-edited `generated/*.toml` (don't — it is autogenerated).
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, it, expect } from 'vitest';

import mcpPublicConfig from '../../src/constants/mcp-public-config.json' with { type: 'json' };

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// tests/admin/ → mcp-server/ → typescript/ → src/ → repo root
const REPO_ROOT = resolve(__dirname, '..', '..', '..', '..', '..');

function expectedToolsLine(): string {
  const toolsToml = mcpPublicConfig.publicTools.map((t) => `"${t}"`).join(', ');
  return `enabled_tools = [${toolsToml}]`;
}

describe('mcp-public-config drift guard', () => {
  describe('publicTools is mirrored in generated/ artifacts', () => {
    const artifacts = [
      'generated/codex_config.workspace-qdrant.toml',
      'generated/codex_config.workspace-qdrant.fastembed.toml',
    ];

    for (const rel of artifacts) {
      it(`${rel} has the canonical enabled_tools line`, () => {
        const path = resolve(REPO_ROOT, rel);
        if (!existsSync(path)) {
          // Fresh clone — artifact has not been generated yet. Skip rather than
          // fail; CI in such a state should run the PS script first.
          console.warn(`[drift-guard] skip: ${rel} not present (run apply-config to generate)`);
          return;
        }
        const content = readFileSync(path, 'utf8');
        expect(content).toContain(expectedToolsLine());
      });
    }
  });

  describe('codex timeouts mirror the JSON', () => {
    it('startup_timeout_sec is a positive integer', () => {
      expect(Number.isInteger(mcpPublicConfig.codex.startup_timeout_sec)).toBe(true);
      expect(mcpPublicConfig.codex.startup_timeout_sec).toBeGreaterThan(0);
    });
    it('tool_timeout_sec is a positive integer', () => {
      expect(Number.isInteger(mcpPublicConfig.codex.tool_timeout_sec)).toBe(true);
      expect(mcpPublicConfig.codex.tool_timeout_sec).toBeGreaterThan(0);
    });

    it('generated/codex_config.workspace-qdrant.toml uses JSON timeouts', () => {
      const path = resolve(REPO_ROOT, 'generated/codex_config.workspace-qdrant.toml');
      if (!existsSync(path)) {
        console.warn('[drift-guard] skip: generated/codex_config.workspace-qdrant.toml not present');
        return;
      }
      const content = readFileSync(path, 'utf8');
      expect(content).toContain(`startup_timeout_sec = ${mcpPublicConfig.codex.startup_timeout_sec}`);
      expect(content).toContain(`tool_timeout_sec = ${mcpPublicConfig.codex.tool_timeout_sec}`);
    });
  });

  describe('publicTools is mirrored in TRACKED templates/docs (no skip — these files exist)', () => {
    // Unlike generated/ (gitignored, so the guard above self-skips in CI),
    // these mirrors are checked into the repo and MUST carry the canonical
    // enabled_tools line. This is the guard that failed to exist when `help`
    // was added to publicTools and every Codex client provisioned from the
    // fork kit kept filtering it out (PR #358 review).
    const trackedMirrors = [
      'templates/fork-kit/codex_config.template.toml',
      'docs/fork-kit/02-clientes-claude-codex.md',
    ];

    for (const rel of trackedMirrors) {
      it(`${rel} carries the canonical enabled_tools line`, () => {
        const content = readFileSync(resolve(REPO_ROOT, rel), 'utf8');
        expect(content).toContain(expectedToolsLine());
      });
    }
  });

  describe('admin tools playground mirrors the tool registry', () => {
    it('PG_TOOLS has an entry for every public and internal tool', () => {
      // The playground registry in admin/static/app.js is plain browser JS and
      // cannot import the JSON, so it is pinned here instead: a tool missing
      // from PG_TOOLS is invisible in the admin UI even though the invoke
      // route accepts it.
      const appJs = readFileSync(
        resolve(__dirname, '..', '..', 'src', 'admin', 'static', 'app.js'),
        'utf8'
      );
      for (const tool of [...mcpPublicConfig.publicTools, ...mcpPublicConfig.internalTools]) {
        expect(appJs, `PG_TOOLS entry for ${tool}`).toContain(`{ name: '${tool}'`);
      }
    });
  });

  describe('publicTools ⊆ KNOWN_TOOLS (tool-dispatcher accepts every public tool)', () => {
    // Re-derive what tool-dispatcher.ts computes to confirm the union is consistent.
    it('no public tool is missing from the server registry', () => {
      const knownTools = [...mcpPublicConfig.publicTools, ...mcpPublicConfig.internalTools];
      for (const pub of mcpPublicConfig.publicTools) {
        expect(knownTools).toContain(pub);
      }
    });
  });
});
