#!/usr/bin/env tsx
/**
 * Generates build-info.ts with build provenance: a short commit SHA, a build
 * timestamp, and the legacy 4-digit hex build number.
 *
 * Provenance sources, in order: build-arg env vars (WQM_BUILD_SHA /
 * WQM_BUILD_TIME / WQM_BUILD_NUMBER) → `git` → fallback. The env path exists
 * because the Docker build context omits `.git` (see Dockerfile), so `git` fails
 * inside the image; the Makefile/compose pass the real values as build-args. The
 * build TIME always resolves to a real value (env, else now — this script runs
 * at build time) so build-info is never a meaningless constant.
 *
 * Run as part of the build pipeline (npm run build → generate:build-info).
 */

import { execFileSync } from 'child_process';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Try a git command; return '' if git is unavailable (no .git in the layer). */
function tryGit(args: string[]): string {
  try {
    return execFileSync('git', args, { encoding: 'utf-8' }).trim();
  } catch {
    return '';
  }
}

// Short commit SHA: build-arg → git → 'unknown'.
let buildSha = (process.env['WQM_BUILD_SHA'] ?? '').trim();
if (!buildSha) buildSha = tryGit(['rev-parse', '--short', 'HEAD']);
if (!buildSha) buildSha = 'unknown';

// Legacy hex build number (kept for back-compat): env → git commit count → '0000'.
let buildNumber = (process.env['WQM_BUILD_NUMBER'] ?? '').trim();
if (!buildNumber) {
  const count = parseInt(tryGit(['rev-list', '--count', 'HEAD']), 10);
  if (Number.isFinite(count)) buildNumber = count.toString(16).toUpperCase().padStart(4, '0');
}
if (!buildNumber) buildNumber = '0000';

// Build time: always real — the env build-arg if provided, else now.
const buildTime = (process.env['WQM_BUILD_TIME'] ?? '').trim() || new Date().toISOString();

// JSON.stringify keeps the emitted literals safe regardless of the input value.
// The `: string` annotations widen the types so consumers can compare them
// (e.g. BUILD_SHA !== 'unknown') without tsc flagging a literal-type mismatch.
const content = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const BUILD_NUMBER: string = ${JSON.stringify(buildNumber)};
export const BUILD_SHA: string = ${JSON.stringify(buildSha)};
export const BUILD_TIME: string = ${JSON.stringify(buildTime)};
`;

writeFileSync(join(__dirname, '..', 'src', 'build-info.ts'), content);
console.log(`Build info: number=${buildNumber} sha=${buildSha} time=${buildTime}`);
